### ISSUE TITLE
Enhance Website Responsiveness for Mobile Devices

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [ritika728/Wellness_Wave#1]
website is currently facing responsiveness issues 
please assign me this under JWOC'24 when the coding phase starts

**Comment by ritika728** [comment]
Mentees needs to create an issue after the coding period starts. Closing this issue.

**Comment by NaveenChandraAdhikari** [comment]
@ritika728 open all the issue as coding phases starts from 15 of JWOC

**Comment by ritika728** [comment]
@NaveenChandraAdhikari kindly refer to the guidelines. No issues created before 15th Jan would be considered under JWOC.
