### ISSUE TITLE
 Implement Contact Us Section with Validations

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#10]
The website currently lacks a Contact Us section on the **HomePage**, hindering users from easily reaching out. This issue aims to create a Contact Us section and implement proper form validations 
- Design the Contact Us form, including fields for name, email, subject, and message.
- Integrate form validation mechanisms to ensure that required fields are filled, and data entered is in the correct format.

**Comment by Hemant5104** [comment]
I would like to work on that issue under JWOC'24

**Comment by suruchichoudhary122** [comment]
hey @ritika728, I would like to work on this problem. under JWOC'24

**Comment by ritika728** [comment]
@Hemant5104 @suruchichoudhary122 Only the comments made after the coding period starts would be considered

**Comment by PranavBarthwal** [comment]
@ritika728 I would like to work on this issue under JWOC'24. Please assign this to me.
Sample : 
![Screenshot 2024-01-14 201502](https://github.com/ritika728/Wellness_Wave/assets/110532770/614abcf7-e507-44f5-a957-504395e363c1)

it will also have validations
![Screenshot 2024-01-14 204207](https://github.com/ritika728/Wellness_Wave/assets/110532770/369bfe06-7dbd-4ace-8038-829ab29e4a1e)

**Comment by Sneha6003** [comment]
I would like to work on that issue under JWOC.

**Comment by Hemant5104** [comment]
I would like to work on that issue under JWOC'24

**Comment by ritika728** [comment]
@PranavBarthwal go ahead 👍
