### ISSUE TITLE
Hover option for "whats in it" section 

### ISSUE THREAD

**Issue by thesri** [ritika728/Wellness_Wave#100]
even after selecting particular option like contact , no special effect is there to stand it out. so a hover option would be better and look good, please assign this under jwoc 2024

**Comment by ritika728** [comment]
@thesri there is an hover effect in this section. Please share screenshot/elaborate more on what changes would you like to do

**Comment by thesri** [comment]
sorry my bad. really sorry

**Comment by ritika728** [comment]
No worries! Happy contributing 🌟
