### ISSUE TITLE
[Feat] Adding Wellness Wave enrollment form

### ISSUE THREAD

**Issue by Sneha6003** [ritika728/Wellness_Wave#104]
### Describe
I would like to add an enrollment form where people can enroll for wellness programs like yoga, meditation sessions, etc.

### Screenshots
If applicable, add screenshots to help explain your problem

**CheckList**
- [X] I'm a JWOC'24 Contributor
- [X] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@Sneha6003 where would you like to add this form ?

**Comment by Sneha6003** [comment]
@ritika728 in the nav bar which will direct to a new page for enrollment and will show pricing table as well.

**Comment by ritika728** [comment]
@Sneha6003 sounds good. Assigned

**Comment by ritika728** [comment]
@Sneha6003 sounds good! 
I'll consider changing the difficulty label for sure after reviewing the pull request
