### ISSUE TITLE
Home And Other section UI : Using Card With Different Styles.

### ISSUE THREAD

**Issue by vishal2005025** [ritika728/Wellness_Wave#106]
### Describe

I would like to improve the home section and other sections like physical health , mental health etc. UI using cards with different styles with enhancement in content . Also it will make the website responsive by using cards .

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@vishal2005025 the tracking & wellness pages consists of cards. Using cards on home page won't look appealing. 
If you have any new ideas of improving the UI, please consider opening a new issue.
