### ISSUE TITLE
Adding TDEE Calculator

### ISSUE THREAD

**Issue by daksh1210jain** [ritika728/Wellness_Wave#107]
### Describe
calculator to calculate your daily calorie intake 

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@daksh1210jain the calculator to estimate the daily calorie intake is already present in the tracking section of the website. Hence, I would be closing this issue
