### ISSUE TITLE
[STYLE] improvng the header and navbar styling

### ISSUE THREAD

**Issue by daksh1210jain** [ritika728/Wellness_Wave#108]
### Describe
adding few features to header and navbar 
### Screenshots
If applicable, add screenshots to help explain your problem

**CheckList**
- [x ] I'm a JWOC'24 Contributor
- [ x] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by ritika728** [comment]
@daksh1210jain please elaborate on what features you would like to add to the header & navbar

**Comment by daksh1210jain** [comment]
Mam i would like to add some background to the navbar and header and also some good effects to button basically improve their styling

**Comment by ritika728** [comment]
@daksh1210jain assigned
