### ISSUE TITLE
Design & Implement a Favicon

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#11]
The current website lacks a favicon. This issue aims to implement a favicon across all pages, ensuring a consistent and visually recognizable icon in browser tabs.

**Comment by diyabhandari** [comment]
Hi, can you please assign me this issue for JWoC '24?

**Comment by ritika728** [comment]
@diyabhandari Only the comments made after the coding period starts would be considered

**Comment by ritika728** [comment]
@ayesha-2101 go ahead

**Comment by ritika728** [comment]
@ayesha-2101 do show me the favicon here in this issue itself, before adding it.

**Comment by ayesha-2101** [comment]
> @ayesha-2101 do show me the favicon here in this issue itself, before adding it.
![wave (1)](https://github.com/ritika728/Wellness_Wave/assets/112239598/bd0ab848-5ce4-47f1-86cb-c23771e5ab5c)
I found this relevant, and it coordinates with the font color of the headings on the website. Should I go with this?

**Comment by ritika728** [comment]
@ayesha-2101 looks good 👍

**Comment by ayesha-2101** [comment]
@ritika728 I have made the pull request.
