### ISSUE TITLE
The footer is floating above [STYLE]

### ISSUE THREAD

**Issue by MADHURYAHAIT** [ritika728/Wellness_Wave#114]
### Describe
A clear and concise description of what would you like to improve.
![Uploading Screenshot 2024-01-24 at 9.05.26 PM.png…]()

### Screenshots
If applicable, add screenshots to help explain your problem

**CheckList**
- [ ] I'm a JWOC'24 Contributor
- [ ] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by MADHURYAHAIT** [comment]
@ritika728 Allow me to fix it : )

**Comment by ritika728** [comment]
@MADHURYAHAIT go ahead
