### ISSUE TITLE
[STYLE] Improve the UI of the Homepage

### ISSUE THREAD

**Issue by akarshi19** [ritika728/Wellness_Wave#115]
### Describe
I want to improve the UI of the website. I have attached the link of the file of updated UI 
https://www.figma.com/file/A2bAxkRLWeq2xtIcSnPhVE/Untitled?type=design&node-id=0%3A1&mode=design&t=5zPCUp8BROUPaR0E-1
### Screenshots
![Screenshot 2024-01-25 111055](https://github.com/ritika728/Wellness_Wave/assets/93787305/3ddf27bd-74a1-48f7-b66f-62d273cc6746)

**CheckList**
- [X] I'm a JWOC'24 Contributor
- [X] I've checked the existing issues, this issue is not a duplicate

**Comment by akarshi19** [comment]
Please assign me this issue under'JWOC'2024'

**Comment by ritika728** [comment]
@akarshi19 this is not the requirement of the project as of now, hence I would be closing this issue.
