### ISSUE TITLE
Implement Two Health-Related Calculators

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#12]
- Add two new health calculators to the Tracking Page
- Ensuring consistency with the existing Calculator (BMI, Sleep etc.) pages in terms of styling and user interface.  
- Do not add a new box, instead replace the XYZ Calculators with the newly added calculators.

**Comment by Aswinr24** [comment]
Hey would like to work on this issue

**Comment by isadarsh** [comment]
Hey I could add couple of new Health Calculators.
- I suppose something like:
 > water hydration levels/ calorie intake/ body fat calculator might work.

Please do assign me this issue under JWOC'24 label.

Thanks.

**Comment by ritika728** [comment]
@isadarsh yes, add any two calculators from the ones you've mentioned. Go ahead 👍

**Comment by NaveenChandraAdhikari** [comment]
@ritika728 can i add more health calculators . I have raised the  before  but as the coding period not started you closed that issues ..Assign me this under JWOC

**Comment by ritika728** [comment]
@NaveenChandraAdhikari you are already assigned to issue #20. Moreover, someone else is working on this issue as of now.
