### ISSUE TITLE
[STYLE]: Sidebar

### ISSUE THREAD

**Issue by AaadityaG** [ritika728/Wellness_Wave#120]
### Describe
I will replace current sidebar with an apealing sidebar which will come(slowely) from right/left side after clicking on hamburger. 

### Screenshots

https://github.com/ritika728/Wellness_Wave/assets/114663382/73631fe0-a92e-48a0-91b2-8628f1d9c8df

**CheckList**
- [X] I'm a JWOC'24 Contributor
- [X] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@AaadityaG assigned

**Comment by AaadityaG** [comment]
> @AaadityaG assigned

@ritika728 at least give it a medium tag..🥲

**Comment by ritika728** [comment]
@AaadityaG don't worry, I'll consider changing it after reviewing the Pull Request
