### ISSUE TITLE
Introduction of Medical Condition section

### ISSUE THREAD

**Issue by Hemant5104** [ritika728/Wellness_Wave#125]
Mam ,I would to like to add section called **Medical Condition** in which there are different medical condition people are suffering.So that users can be aware of different medical conditions , use different calculators to calculate their body requirements and it will also increase our website engagement time.
Please add this under JWOC'24 and please add a difficulty tag .
UI will be card-based.
Should I add it in navbar or wellness section or what's in it section.
**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@Hemant5104 add it in the wellness section
