### ISSUE TITLE
[BUG] Footer issue

### ISSUE THREAD

**Issue by debuuuu007** [ritika728/Wellness_Wave#126]
**Describe the bug**
In the Rateus page footer, social icons cannot be seen.

**Screenshots**
![Screenshot 2024-01-26 213558](https://github.com/ritika728/Wellness_Wave/assets/121102183/ee743b29-7bf7-4bfb-80b8-f281d1ece2a8)

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@debuuuu007 assigned

**Comment by thesri** [comment]
@ritika728 please assign this under jwoc 2024, if the assigned mentee didnt do it in time
