### ISSUE TITLE
[BUG] : Not Responsive on Card Layout

### ISSUE THREAD

**Issue by this-is-yaash** [ritika728/Wellness_Wave#127]
**Describe the bug**
Upon hovering on the card, the text inside the card were overlapping outside the card height

**Screenshots**
![image](https://github.com/ritika728/Wellness_Wave/assets/84762257/b6a91535-a65a-4e74-8c02-8ec549241986)

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

If this issue is valid then assign me to work on this issue under **JWOC**

**Comment by ritika728** [comment]
@this-is-yaash the cards are responsive and are working fine, can you please pull all the changes & then let me know if the problem still persists.
