### ISSUE TITLE
Making Navbar stay fixed while scrolling

### ISSUE THREAD

**Issue by isadarsh** [ritika728/Wellness_Wave#13]
### Feature
The top navbar-card  of website does not moves as we scroll down.

**The navbar goes away while scrolling down.**

**Checklist**
- [x] I have checked the existing issues.
- [x] I follow [Contributing Guidelines](https://github.com/ritika728/Wellness_Wave#contribution-guidelines) of this project
- [x] I am JWOC'24 Contributor.

**Comment by isadarsh** [comment]
Okay

**Comment by Seema-bedara** [comment]
Hi,                                                                                                                                                                                                                                                                                                                                                                                                                               I am interested in contributing to this as a part of JWOC.`24 Please assign it to me.

**Comment by ritika728** [comment]
@Seema-bedara assigned

**Comment by Seema-bedara** [comment]
Thank you

**Comment by ritika728** [comment]
updates on this issue @Seema-bedara

**Comment by thatguywhocode** [comment]
Hey @ritika728  , I want to work on this issue under JWOC.

**Comment by ritika728** [comment]
@thatguywhocode if there is no pull request for this issue by tomorrow noon, you would be assigned to work on this

**Comment by Seema-bedara** [comment]
> updates on this issue @Seema-bedara

@ritika728  Sorry for late . 
I have raised a PR , Please review it  and let me know if any changes you want .

**Comment by ritika728** [comment]
> > updates on this issue @Seema-bedara
> 
> @ritika728 Sorry for late . I have raised a PR , Please review it and let me know if any changes you want .

No worries, I'll review it in a while
