### ISSUE TITLE
Enhancement of the calculators

### ISSUE THREAD

**Issue by madhurima316** [ritika728/Wellness_Wave#130]
### Describe
I would like to change the font colour for result in BMI CALCULATOR section, the texts in PROTEIN INTAKE CALCULATOR section, the calculated pace in PACE CALCULATOR section and for the other calculators in tracking section (because in some the font color coincides with the background) . 

### Screenshots

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by madhurima316** [comment]
Please assign me this issue under JWOC 2024

**Comment by madhurima316** [comment]
Please assign me this issue under JWOC 2024.

**Comment by ritika728** [comment]
@madhurima316 since you are already working on an issue under this project, this issue can't be assigned to you until the previous issue gets closed.

**Comment by madhurima316** [comment]
Please assign me this issue under JWOC 2024.

**Comment by ritika728** [comment]
@madhurima316 assigned
