### ISSUE TITLE
[BUG] Tracking page issue.

### ISSUE THREAD

**Issue by nepalivai** [ritika728/Wellness_Wave#135]
**Describe the bug**
There is a gap between the nav and top bar.

**Screenshots**
<img width="960" alt="image" src="https://github.com/ritika728/Wellness_Wave/assets/108126089/3323a7b4-cc10-44a8-a347-0e322358a1ee">

**CheckList**
- [ ] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by ritika728** [comment]
@nepalivai assigned

**Comment by vishal2005025** [comment]
please assign it to me under JWOC'2024.

**Comment by ritika728** [comment]
@vishal2005025 assigned
