### ISSUE TITLE
[STYLE] add new navbar 

### ISSUE THREAD

**Issue by AftabMankapure** [ritika728/Wellness_Wave#139]
### Describe
add new nav bar 

### Screenshots
Current  
![cc](https://github.com/ritika728/Wellness_Wave/assets/125949765/f60b0725-f7e1-4973-9d98-60f8225d0da1)

new 

![nn](https://github.com/ritika728/Wellness_Wave/assets/125949765/88ebed41-ad86-4b40-9bef-2e42f4e2f0c8)

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

**Comment by vishal2005025** [comment]
I Would like to work on this issue.
please assign it to me under JWOC'2024

**Comment by AftabMankapure** [comment]
@vishal2005025 bro i raised this issue
pls check any other
@ritika728 assign me under jwoc

**Comment by ritika728** [comment]
@AftabMankapure go ahead

**Comment by ritika728** [comment]
@AftabMankapure go ahead
Make sure to make the required changes in the navbar of all the existing pages. 
Also, black background color doesn't look appealing, consider a different color which matches with the theme of the website

**Comment by AftabMankapure** [comment]
instead of background image we well add some color white or any other 
and we can add dark mode button to change theme 


pls check other issue raised by me 
if you assign issue fast we can make a beautiful website

**Comment by AftabMankapure** [comment]
for navbar color i can show some sample after some time

**Comment by AftabMankapure** [comment]
https://github.com/ritika728/Wellness_Wave/assets/125949765/09df3e81-602e-4dc6-b6cb-6928f6e1dd4b

can i go with #0e1525 color or any

**Comment by AftabMankapure** [comment]
we can add dark mode also

**Comment by AftabMankapure** [comment]
Can I go ahead

**Comment by ritika728** [comment]
@AftabMankapure since only one issue under a project can be assigned at a time, please proceed with improving the navbar, for which this issue was originally raised. Additionally, someone is already working on an issue to implement the dark mode theme for this website.

Moreover, kindly consider pinging me in the Discord group after raising an issue for a quicker assignment.

**Comment by ritika728** [comment]
> wwNs.mp4 
> can i go with #0e1525 color or any

Yes, this seems good to go with
