### ISSUE TITLE
Mental health & Spiritual Health Sections Enhancement 

### ISSUE THREAD

**Issue by debuuuu007** [ritika728/Wellness_Wave#14]
I would like to work on that issue under JWOC.

**Comment by ritika728** [comment]
@debuuuu007 what kind of modification & content addition are you hoping to make ?

**Comment by debuuuu007** [comment]
First of all i saw that the alignment of the data written in mental health section is not that well. So I will correct it at first. 

Then to be honest, I am a spiritual person so I want to add some content in the spiritual section.

**Comment by ritika728** [comment]
@debuuuu007 go ahead

**Comment by debuuuu007** [comment]
Another doubt from my side. 

Is that the application can only seen through github pages, I cannot see the production part by vercel. 

Is it normal or I need to do something to see the vercel one.

**Comment by ritika728** [comment]
@debuuuu007 
The Vercel thing is now done 
Also, along with the alignment of the mental health page, do work on its styling part like:
- Adding a background image
- Relevant text fonts
- suitable pictures where needed (in accordance with the content)

**Comment by debuuuu007** [comment]
Mam i do not think that picture matter that much if the content is strong. And as the project is on well being and peace of mind such thing, I personally do not prefer to add images in the page. 

Yes, a background image and text font would charm the page for sure.

**Comment by ritika728** [comment]
@debuuuu007 alright, go with whatever seems best for the page in accordance with the theme
