### ISSUE TITLE
[STYLE] improvement in footer 

### ISSUE THREAD

**Issue by AftabMankapure** [ritika728/Wellness_Wave#140]
### Describe
improvement in footer alignment background color hover effect and some new style 

### Screenshots
current 
![ff](https://github.com/ritika728/Wellness_Wave/assets/125949765/d89236d3-871c-4f1b-8c1e-e936e5c0c54d)

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

**Comment by vishal2005025** [comment]
I Would like to work on this issue.
please assign it to me under JWOC'2024

**Comment by AftabMankapure** [comment]
@vishal2005025  bro i raised this issue 
pls check any other 
@ritika728  assign me under jwoc

**Comment by vishal2005025** [comment]
Mam , please assign it to me under JWOC'2024.

**Comment by AftabMankapure** [comment]
assign me under jwoc

**Comment by ritika728** [comment]
@AftabMankapure assigned

**Comment by AftabMankapure** [comment]
can i replace this ""Sweat Today,
Shine Tomorrow.
Embrace the Burn,
Sculpt the Strength.
Your Journey,
Your Body,
Your Triumph.
Elevate your Fitness,
Elevate your Life."
"
with "Elevate Your Fitness. Ignite Your Life."

**Comment by AftabMankapure** [comment]
![f1](https://github.com/ritika728/Wellness_Wave/assets/125949765/2e2878df-c85b-44ee-af78-b8ccd92e1b22)
it is ok

**Comment by AftabMankapure** [comment]
which social link i can add and link for it 
github, facebook, or any other
