### ISSUE TITLE
[STYLE] section background is not good 

### ISSUE THREAD

**Issue by AftabMankapure** [ritika728/Wellness_Wave#141]
### Describe
remove the section background and make it transparent

### Screenshots
current 
![2](https://github.com/ritika728/Wellness_Wave/assets/125949765/3dadaf84-547c-4227-80bf-cf66716c6c48)

new 
![1](https://github.com/ritika728/Wellness_Wave/assets/125949765/0b91ea2e-b3e9-4efb-b512-79c0aa190bc4)

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by vishal2005025** [comment]
Mam, please assign it to me under JWOC'2024
