### ISSUE TITLE
UI of home page in phone mode is not proper

### ISSUE THREAD

**Issue by prasukjain07** [ritika728/Wellness_Wave#144]
**Describe the bug**

**Screenshots**

**CheckList**
- [ ] I'm a JWOC'24 Contributor
- [ ] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by ritika728** [comment]
@prasukjain07 kindly elaborate more and share the screenshots of the problem for a better understanding
