### ISSUE TITLE
[STYLE] Add Cookie Consent Box

### ISSUE THREAD

**Issue by Sneha6003** [ritika728/Wellness_Wave#146]
### Describe
 Cookies help to ensure the user gets the best experience on the website so I would like to add a cookie consent box.

### Screenshots
If applicable, add screenshots to help explain your problem

**CheckList**
- [X] I'm a JWOC'24 Contributor
- [X] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by ritika728** [comment]
@Sneha6003 assigned
