### ISSUE TITLE
[OTHER]Creation of a feedback page 

### ISSUE THREAD

**Issue by thesri** [ritika728/Wellness_Wave#149]
### Describe
A clear and concise description of what would you like to add/improve.
A feedback page to know the user experience ant to improve the services, please assign this to me under jwoc 2024 

### Screenshots
If applicable, add screenshots to help explain your problem
![Uploading image.png…]()

**CheckList**
- [x ] I'm a JWOC'24 Contributor
- [ x] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@thesri there is already a rate us page present in the website where user can provide the feedback. The screenshot you have added is not uploaded properly. Kindly elaborate more & attach an appropriate screenshot

**Comment by thesri** [comment]
> @thesri there is already a rate us page present in the website where user can provide the feedback. The screenshot you have added is not uploaded properly. Kindly elaborate more & attach an appropriate screenshot

![h](https://github.com/ritika728/Wellness_Wave/assets/98333833/ce302045-ee6e-4d21-838d-7c956f3a2d83)
like this, like this is for a travel website i want to make a similar one for this website
