### ISSUE TITLE
[OTHER] : Introduce Productivity Tools page

### ISSUE THREAD

**Issue by PranavBarthwal** [ritika728/Wellness_Wave#151]
### Describe
I would like to add a productivity tools page in which we can add different productivity tools like pomodoro timer

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@PranavBarthwal please elaborate on how this productivity tool is relevant in terms of this wellness project

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal please elaborate on how this productivity tool is relevant in terms of this wellness project

Like instead of productivity tools we can name it as Wellness tools, in which users will we provided with some real resources like guided meditation, yoga, Peaceful sounds, white noises and other tools that can help them with their wellness.
