### ISSUE TITLE
Add Favicon to Enhance Website Branding

### ISSUE THREAD

**Issue by rahat2134** [ritika728/Wellness_Wave#16]
Improve the website's visual identity by adding a favicon. A favicon is a small icon displayed in the browser's address bar and tabs, contributing to a more professional and recognizable branding experience.

**Tasks:**
1. Design or select a suitable favicon that aligns with the website's brand.
2. Add the favicon image file to the project's assets.
3. Update the HTML code to include the favicon and ensure proper rendering across browsers.
4. Test the favicon's display on various devices and browsers for consistency.

**Problems:**
1. **Missing Favicon:**
   - The website currently lacks a favicon, resulting in a generic icon or no icon at all in the browser's address bar and tabs.

**Solution:**
   - Adding a favicon enhances the website's branding and provides users with a recognizable visual cue.

**Steps to Reproduce:**
1. Visit the website and observe the absence of a favicon in the browser's address bar and tabs.
2. After the issue is resolved, revisit the website and confirm the presence of the newly added favicon.
<img width="183" alt="Screenshot 2024-01-15 at 2 05 31 AM" src="https://github.com/ritika728/Wellness_Wave/assets/136263179/cbc3e0d4-0329-4b73-9f24-cce8ae4eac5a">

**Comment by rahat2134** [comment]
@ritika728 assign me this issue after issue #15 under JWOC. Thank You.

**Comment by ritika728** [comment]
Issue #11 is covering the favicon addition. Hence, I would close this issue.
