### ISSUE TITLE
[BUG] Absence of navbar in all calculator

### ISSUE THREAD

**Issue by AftabMankapure** [ritika728/Wellness_Wave#161]
**Describe the bug**
Absence of navbar in all calculator

**Screenshots**

**CheckList**
- [x] I'm a JWOC'24 Contributor
- [x] I've checked the existing issues, this issue is not a duplicate

**Comment by ritika728** [comment]
@AftabMankapure navbar is present in all the calculators, they just need to be updated in accordance with the current navbar (take the index page for eg.) 
Go ahead with this
