### ISSUE TITLE
[BUG] Improve the Hamburger

### ISSUE THREAD

**Issue by SohanRC** [ritika728/Wellness_Wave#167]
**Describe the bug**

The hamburger is not clearly visible . Improve the hamburger and replace it with a new one in each and every page.

**Screenshots**

![Screenshot 2024-02-07 010753](https://github.com/ritika728/Wellness_Wave/assets/124901633/1bb4d3c0-20b4-471d-8b7e-aff1291cf440)

**CheckList**
- [X] I'm a JWOC'24 Contributor
- [X] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by SohanRC** [comment]
@ritika728 Please review this issue

**Comment by ritika728** [comment]
@SohanRC assigned
