### ISSUE TITLE
Standardize Navigation Bar Dynamics Across All Sections

### ISSUE THREAD

**Issue by rahat2134** [ritika728/Wellness_Wave#17]
Ensure a consistent user experience by standardizing the navigation bar dynamics across all sections of the website. Currently, there is a discrepancy in the behavior of the navigation bar, particularly in the wellness section. This issue aims to provide a seamless and uniform navigation experience throughout the entire website.

**Tasks:**
1. Identify the variations in navigation bar dynamics within different sections.
2. Analyze the desired behavior and interactions for the navigation bar across all sections.
3. Implement JavaScript functionality or adjust existing code to standardize the navigation bar's behavior.
4. Test the changes on various pages to ensure uniformity in navigation bar dynamics.

**Problems:**
1. **Inconsistent Navigation Bar Behavior:**
   - The navigation bar behaves differently in the wellness section compared to other sections, leading to an inconsistent user experience.

**Solution:**
   - Standardizing the navigation bar dynamics ensures a cohesive and predictable navigation experience for users across all sections.

**Steps to Reproduce:**
1. Navigate to various sections on the website and observe the navigation bar's behavior.
2. Specifically, note any discrepancies in the dynamics when transitioning between sections.
3. After the issue is resolved, revisit the sections and verify that the navigation bar now exhibits consistent behavior.
<img width="1151" alt="Screenshot 2024-01-15 at 2 07 39 AM" src="https://github.com/ritika728/Wellness_Wave/assets/136263179/222ebf88-32a4-4d95-8536-0648d5c9a312">
<img width="653" alt="Screenshot 2024-01-15 at 2 07 59 AM" src="https://github.com/ritika728/Wellness_Wave/assets/136263179/2fc099cc-c831-4b0a-9197-a6860e507a75">

**Comment by rahat2134** [comment]
@ritika728 assign this issue under JWOC after issue #16 done by me. Thank You.

**Comment by Jenis07** [comment]
I would like to work on this issue under JWOC. Please assign it to me
