### ISSUE TITLE
[STYLE] Improve the Footer

### ISSUE THREAD

**Issue by Surajit0573** [ritika728/Wellness_Wave#173]
### Describe

I want to fix the UI of navbar of tracking  page, Wellness page, Enroll page and Rate us page.

### Screenshots
![image](https://github.com/ritika728/Wellness_Wave/assets/111490250/cee17bf2-304f-4876-badb-07f6f37c8469)
![image](https://github.com/ritika728/Wellness_Wave/assets/111490250/1577dc9f-2677-4cae-9dfd-bd68e7b57b58)

**CheckList**
- [X] I'm a JWOC'24 Contributor
- [ ] I've checked the existing issues, this issue is not a duplicate

(Tip - place an "x" between the square brackets to check mark)

**Comment by Surajit0573** [comment]
@ritika728, Please review this issue.

**Comment by ritika728** [comment]
@Surajit0573 assigned
