### ISSUE TITLE
Wellness Wave Navigation

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#176]
When the user clicks on Wellness Wave in the navbar, he/she must be directed to the home (index) page. 
Correct this navigation in all the existing pages.

**Comment by SohanRC** [comment]
Assign me under JWOC 2024

**Comment by Anushkabh** [comment]
kindly assign this issue under jwoc @ritika728

**Comment by AftabMankapure** [comment]
Assign  me under JWOC
@ritika728  Sorry for this issue navbar is created by me 
but i feel and many of this website use this technique to move home page as logo in navbar
