### ISSUE TITLE
[BUG] Tracking Page Inconsistency

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#177]
The below mentioned calculators (refer to the screenshot) are not consistent in terms of other calculators on the tracking page. 
Make the required changes so that the divisions are correctly coded. 

**Screenshot**
![1](https://github.com/ritika728/Wellness_Wave/assets/91181981/e964ed0b-fc0e-4029-879f-86a88f4a07bf)

**Comment by Surajit0573** [comment]
Assign me under JWOC 2024
