### ISSUE TITLE
UI improvement of text-to-speech

### ISSUE THREAD

**Issue by KumariAnkita04** [ritika728/Wellness_Wave#19]
I want to enhance the UI of text-to-speech page. It look so dull. Also the font size is not looking appropriate.

**Comment by ritika728** [comment]
@KumariAnkita04 since you are already assigned to an issue, this issue won't be assigned to you until the previous one gets closed.

**Comment by ritika728** [comment]
@KumariAnkita04 now, you can work on this issue. Please share relevant image of what would you like to improve/add

**Comment by KumariAnkita04** [comment]
Also I want to do it under JWoC'24

**Comment by ritika728** [comment]
alright @KumariAnkita04 , but what exactly do you wish to improve ?

**Comment by ritika728** [comment]
@KumariAnkita04 go ahead
