### ISSUE TITLE
 Enhance Website Responsiveness for Mobile Devices 

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [ritika728/Wellness_Wave#20]
website is currently facing responsiveness issues
please assign me this under JWOC'24 when the coding phase starts

**Comment by ritika728** [comment]
@NaveenChandraAdhikari go for it. Make the entire website responsive for all the devices (exclude navbar)

**Comment by ritika728** [comment]
@NaveenChandraAdhikari updates on this issue

**Comment by NaveenChandraAdhikari** [comment]
..as my exams are going on... I'll surely be merging PR  after tomorrow

**Comment by ritika728** [comment]
@NaveenChandraAdhikari Kindly raise the PR for it by tomorrow night, else it would be up for grab as per the rules.

**Comment by shahil-afroz** [comment]
Can you assign this to me under JWOC 24.....I want to contribute in this project...

**Comment by krittika2004** [comment]
@ritika728 Please assign this issue to me under JWOC 2024

**Comment by ritika728** [comment]
@shahil-afroz assigned

**Comment by ritika728** [comment]
@shahil-afroz updates ?

**Comment by Sneha6003** [comment]
I would like to work on this issue under JWOC.

**Comment by akarshi19** [comment]
Please assign me this issue under 'JWOC'2024'

**Comment by ritika728** [comment]
@akarshi19 assigned

**Comment by Sneha123-zudo** [comment]
I am interested in solving this issue
