### ISSUE TITLE
Create FAQ section with accordion

### ISSUE THREAD

**Issue by AaadityaG** [ritika728/Wellness_Wave#23]
please allow me to work on it under jwoc tag!

**Comment by ritika728** [comment]
@AaadityaG Where will you place the FAQ Section ?

**Comment by ritika728** [comment]
@AaadityaG you can create the testimonial page & can add the FAQ section there (only FAQ, no testimonials). Works ?

**Comment by AaadityaG** [comment]
Ok

**Comment by Hemant5104** [comment]
I want to work on that issue under JWOC'24
