### ISSUE TITLE
Tracking Section  boxes not aligned properly

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [ritika728/Wellness_Wave#3]
![Screenshot from 2024-01-13 22-13-23](https://github.com/ritika728/Wellness_Wave/assets/44281971/00538a7a-a3fd-4693-b900-b4c59dc3535c)
assign me this under jwoc24

**Comment by ritika728** [comment]
Mentees needs to create an issue after the coding period starts. Closing this issue for now.
