### ISSUE TITLE
Build testimonials page

### ISSUE THREAD

**Issue by PranavBarthwal** [ritika728/Wellness_Wave#32]
Build a testimonials page which will be linked to the the testimonials button in the navbar.

**Comment by ritika728** [comment]
@PranavBarthwal go ahead
Do not create a new page, add the testimonials in the FAQ page itself, below the FAQs

**Comment by Anoushka-Aggarwal** [comment]
pls assign it to me @ritika728

**Comment by diyabhandari** [comment]
If required, please assign this issue to me later.

**Comment by ritika728** [comment]
@Anoushka-Aggarwal assigned
