### ISSUE TITLE
Replacing Settings or Contact section with Exercises section 

### ISSUE THREAD

**Issue by Hemant5104** [ritika728/Wellness_Wave#34]
I can add a 30 days workout and Yoga plan with 3 difficulty levels according to user preference . I can place settings option in footer.
Please add this under JWOC'24 and also add the difficulty tag

**Comment by ritika728** [comment]
@Hemant5104 sounds good, can be implemented
Can you please elaborate on what do you exactly mean by placing settings option in footer

**Comment by Hemant5104** [comment]
I can place it below, above or between the terms and conditions link and FAQs link. Anywhere you suggest

**Comment by ritika728** [comment]
@Hemant5104 maybe you can add it on Wellness Page, as a different section, below the existing content instead of adding it in the footer

**Comment by Hemant5104** [comment]
What I meant to say that I can add workout section in navbar or as a separate section in wellness webpage

**Comment by ritika728** [comment]
Don't add it in navbar, just add it as a separate section on wellness page.

**Comment by Hemant5104** [comment]
Please add this under JWOC and mention the difficulty level

**Comment by ritika728** [comment]
No worries, I'll add the labels after reviewing the pull request
