### ISSUE TITLE
Adding more calcualtors 

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [ritika728/Wellness_Wave#4]
Add  calcualtors like Sugar Intake and Body Fat Calculators 
assign me this under jwoc24

**Comment by ritika728** [comment]
Mentees needs to create an issue after the coding period starts. Closing this issue for now.

**Comment by NaveenChandraAdhikari** [comment]
Can you please open all closed issues as coding phase of jwoc starts from 15

**Comment by ritika728** [comment]
@NaveenChandraAdhikari mentees need to create new issues. No issues made before the coding period would be considered under JWOC.
