### ISSUE TITLE
Adding clickable links

### ISSUE THREAD

**Issue by ayesha-2101** [ritika728/Wellness_Wave#5]
While Physical Health and Mental Health have clickable links and lead to more information about this. Emotional Health does not have such a feature. 
I am willing to add a web page for this. Please assign this to me once the coding period starts @ritika728 
![Screenshot 2024-01-14 111153](https://github.com/ritika728/Wellness_Wave/assets/112239598/5a896846-2ff4-48a4-b3a7-79add536e3d4)

**Comment by Hemant5104** [comment]
I can add a clickable link to Spiritual Wellness and and Social Well-Being Heading.I am williing to add a webpage to this . Please assign me this @ritika728 under JWOC'24 once the coding phase starts.
![Screenshot 2024-01-14 125324](https://github.com/ritika728/Wellness_Wave/assets/143774541/d0bbb7da-6355-4d9d-9d44-8b977c339add)

**Comment by ritika728** [comment]
Mentees needs to create an issue after the coding period starts. Closing this issue for now.
