### ISSUE TITLE
Update details in Contact Section

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#50]
Incorporate the following links into the footer section across all existing pages:

1. Twitter: https://twitter.com/ritikatwts
2. Email: ritikamalik100102@gmail.com
3. Github: https://github.com/ritika728
4. LinkedIn: https://www.linkedin.com/in/ritika-malik-must/

Respective icons for these handles already exists. Please ensure that the links are appropriately linked with them.

**Comment by Redclawww** [comment]
I would like to work on this issue

**Comment by thatguywhocode** [comment]
Hey @ritika728 ,assign me this issue under JWOC

**Comment by vishal2005025** [comment]
I have read the issue and go through the code ,I am highly interested to work on it.
please assign it to me under JWOC'2024.

**Comment by krittika2004** [comment]
Hey, @ritika728 I am interested to work on this issue. Please assign this to me under JWOC 2024

**Comment by ritika728** [comment]
@thatguywhocode assigned
@Redclawww according to the guidelines, you must mention that you want to work on this issue under JWOC. I won't be able to assign you to this issue

**Comment by thatguywhocode** [comment]
Hey @ritika728 , I created pr under JWOC.
