### ISSUE TITLE
[BUG] Frequently Asked Questions 

### ISSUE THREAD

**Issue by thatguywhocode** [ritika728/Wellness_Wave#52]
Description: In home page under footer tab, the frequently asked questions tab is not working.
Expected Behaviour: It should open FAQs page.
Screenshots:
![Screenshot 2024-01-19 210215](https://github.com/ritika728/Wellness_Wave/assets/138510462/2943265d-176e-42b5-a302-ef1bdabc53a5)

![Screenshot 2024-01-19 205624](https://github.com/ritika728/Wellness_Wave/assets/138510462/80699a82-be92-4e95-8b72-4441f0de5799)

**Comment by thatguywhocode** [comment]
Hey @ritika728 , kindly assign me this issue under JWOC. Thank You

**Comment by Hemant5104** [comment]
@thatguywhocode  I already fixed the bug and created a PR because it was my assignment and because of some issues , It wasn't working properly.So I just corrected my mistake .Don't mind me !!!!

**Comment by ritika728** [comment]
It was just a minor navigation bug in the link, it's now working as expected. Hence, I would be closing this issue
