### ISSUE TITLE
wellness section UI : use cards with different styles 

### ISSUE THREAD

**Issue by vishal2005025** [ritika728/Wellness_Wave#53]

**Comment by vishal2005025** [comment]
please assign it to me under JWOC'2024.

**Comment by ritika728** [comment]
@vishal2005025 kindly elaborate on what all changes you would like to make

**Comment by akarshi19** [comment]
I would love to work on the UI design of the website. Please assign me this task under JWOC
The changes I will like to make
![Home](https://github.com/ritika728/Wellness_Wave/assets/93787305/230a1a25-aed3-4f7d-8878-301d6e371da1)

**Comment by akarshi19** [comment]
I would love to change the UI of wellness section. Please assign me this task under JWOC'2024
Changes i would like to make
![section](https://github.com/ritika728/Wellness_Wave/assets/93787305/8c015644-fd3e-4cf2-b811-9345f10184a2)

**Comment by vishal2005025** [comment]
I would like to use cards in grid with different styles and hovers with content

**Comment by ritika728** [comment]
@vishal2005025 go ahead

**Comment by ritika728** [comment]
@vishal2005025 updates ?

**Comment by vishal2005025** [comment]
I have completed half of the work and I will created pr till tomorrow..

**Comment by vishal2005025** [comment]
Mam, I have completed this issue and created pull request.
please check..

**Comment by vishal2005025** [comment]
Name : Vishal malyan
Mam, I have created new pr after all the changes.
please check
