### ISSUE TITLE
Rating System

### ISSUE THREAD

**Issue by daksh1210jain** [ritika728/Wellness_Wave#57]
I would like to add a rating system to the website
under JWOC

**Comment by daksh1210jain** [comment]
Kindly assign me this issue

**Comment by ritika728** [comment]
@daksh1210jain where would you add this rating system ? Kindly elaborate/ share relevant screenshot

**Comment by daksh1210jain** [comment]
![image](https://github.com/ritika728/Wellness_Wave/assets/137384322/5fd1c1fc-9917-4575-9c9c-744438ffe3b2)
in the above pic when you will click rate us you will land on a page that will take rating and feedback

**Comment by ritika728** [comment]
@daksh1210jain seems a good addition. Go ahead
