### ISSUE TITLE
Website Redesign

### ISSUE THREAD

**Issue by Redvey** [ritika728/Wellness_Wave#59]
Color Schemes: A more cohesive palette aligned with our brand.
Fonts: A refined selection for improved readability and consistency.
Footer: Streamlined layout for better navigation and aesthetics.
Navbar: Optimized structure for enhanced user experience.

overall enhancing the user experience.

**Comment by ritika728** [comment]
@Redvey assigned

**Comment by ojetunji** [comment]
@ritika728 Can I have a go at this too? I have some inspo for the design
