### ISSUE TITLE
Home Page Clickable link

### ISSUE THREAD

**Issue by Hemant5104** [ritika728/Wellness_Wave#6]
I can turn fitness training into a clickable link that will give the user a roadmap of 4 weeks to do exercise to maintain its  physique.@ritika728 I would like to work on that issue under JWOC
![Screenshot 2024-01-14 130255](https://github.com/ritika728/Wellness_Wave/assets/143774541/44541326-8b76-4e58-b07a-74ff768203e8).

**Comment by ritika728** [comment]
Mentees needs to create an issue after the coding period starts. Closing this issue for now.
