### ISSUE TITLE
FEAT: Customized Scrollbar.

### ISSUE THREAD

**Issue by ramith-kulal** [ritika728/Wellness_Wave#60]
## Issue: 
Add Customized Scrollbar.

**Description:**
I propose adding a customized scrollbar to enhance the visual aesthetics and user experience on the website. 

**screenshots:**
the present scrollbar:
![Screenshot 2024-01-20 093859](https://github.com/ritika728/Wellness_Wave/assets/142984776/f7fc1421-6529-4ef4-8db0-221f762c9c7f)

**Working under JWoC'24**

**Comment by ritika728** [comment]
@ramith-kulal assigned
