### ISSUE TITLE
[ENHANCEMENT NEEDED] IN HOME PAGE AND NAV BAR

### ISSUE THREAD

**Issue by ratnojitsaha** [ritika728/Wellness_Wave#61]
The home page seems fine in normal desktop/laptop windows screen size , it is not optimized for phone screens or sizes for example 375 x 667 more over, The nav options needed to be fixed  as it covers some part of home page and blocks the ABOUT and OUR MISSION sections.

SOLUTION - 
1. media query need for smaller screen sizes
2. ToggleMenu (Hamburger Menu) can be added for the Nav links  or some alignments can be done for home page.     

Screenshot- 
![Screenshot (470)](https://github.com/ritika728/Wellness_Wave/assets/110903082/1097458c-1ad4-4695-89d5-08a781e6838a)

Please Assign me under **** #JWoC 2024 *****

**Comment by ritika728** [comment]
@ratnojitsaha someone else is already working on the responsiveness of the website. 
You can work on just creating a hamburger menu.

**Comment by ritika728** [comment]
@ratnojitsaha updates ?

**Comment by ratnojitsaha** [comment]
@ritika728 sry no updates from my side haven't worked on it, someone in my family passed away . I understand the importance of  quick updates. Please consider an extension of 2 days, will submit u by day after tommorrow.

**Comment by ritika728** [comment]
Alright
