### ISSUE TITLE
Mental health section modification and also content addition.

### ISSUE THREAD

**Issue by debuuuu007** [ritika728/Wellness_Wave#7]
The content inside the mental health tag is not aligned properly. I would like to work on this as well as I would like to contribute some of my ways to improve spiritual wellness. I will do this under JWOC'24. Thank you.

**Comment by ritika728** [comment]
Mentees needs to create an issue after the coding period starts. Closing this issue for now.

**Comment by debuuuu007** [comment]
Ok mam
