### ISSUE TITLE
Add a light and dark mode button .

### ISSUE THREAD

**Issue by Sneha123-zudo** [ritika728/Wellness_Wave#74]
Please assign me this issue

**Comment by ritika728** [comment]
@Sneha123-zudo assigned

**Comment by vermaanurag1532** [comment]
please Assign it to me

**Comment by SohanRC** [comment]
@ritika728 Please assign me this issue ! I would like to work on this under JWOC 2024.

**Comment by ritika728** [comment]
@SohanRC assigned

**Comment by AftabMankapure** [comment]
Assign me

**Comment by AftabMankapure** [comment]
Assign me

**Comment by Sneha6003** [comment]
I would like to work on this issue under JWOC

**Comment by AftabMankapure** [comment]
Assign me under JWOC
![d1](https://github.com/ritika728/Wellness_Wave/assets/125949765/025f36c1-1019-442b-b1b9-ac23877694d3)

![d2](https://github.com/ritika728/Wellness_Wave/assets/125949765/70839d32-a68b-4322-8d62-b82e1e328fec)

**Comment by ritika728** [comment]
@AftabMankapure assigned

**Comment by AftabMankapure** [comment]
pls Add hard label
