### ISSUE TITLE
Improve Calculator Page UI

### ISSUE THREAD

**Issue by diyabhandari** [ritika728/Wellness_Wave#75]
![Screenshot 2024-01-21 183411](https://github.com/ritika728/Wellness_Wave/assets/140702816/c0cc7143-a3d8-4b9d-8aea-880cc9349f44)
I believe that this page can be made to look better by using a different hover property for calculators than underline. Please assign me this issue.

**Comment by ritika728** [comment]
@diyabhandari go ahead

**Comment by diyabhandari** [comment]
thanks !
