### ISSUE TITLE
Standard Responsive Footer 

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#8]
Currently, our website lacks a consistent footer across all pages, which is essential for providing users with important information, links, and a cohesive user experience. This issue aims to address this gap by implementing a standardized footer across the entire website.

**Comment by Hemant5104** [comment]
I would like to work on that issue under JWOC'24

**Comment by ritika728** [comment]
@Hemant5104 only the comments done on/after 15th Jan would be considered

**Comment by Hemant5104** [comment]
I would like to work on that issue under JWOC'24

**Comment by PranavBarthwal** [comment]
@ritika728 I would like to work on this issue under JWOC'24. Please assign this to me.
Sample : 
I'll create a footer on all the pages of the website
![Screenshot 2024-01-14 201502](https://github.com/ritika728/Wellness_Wave/assets/110532770/614abcf7-e507-44f5-a957-504395e363c1)

**Comment by ritika728** [comment]
@Hemant5104 go ahead

**Comment by Hemant5104** [comment]
I have added terms and  conditions in the footer with a quote . what would you like to add in the footer?
![Screenshot 2024-01-15 144911](https://github.com/ritika728/Wellness_Wave/assets/143774541/bbed5bd1-060c-49ce-bbda-0edda5a961df)
![Screenshot 2024-01-15 144923](https://github.com/ritika728/Wellness_Wave/assets/143774541/66ff5b98-c8ec-40e8-80f5-b19c99f54492)

**Comment by Hemant5104** [comment]
Contact us is already provided in the homepage .Would you like to add hover over terms and conditions link ?

**Comment by ritika728** [comment]
@Hemant5104 yes, add the hover effect. Also, add the icons for Email, LinkedIn, Twitter & Github. Do not add any links in them as for now

**Comment by Hemant5104** [comment]
I added the hover effect on terms and condition link and added the icons of linkedin, github ,twitter, email.Anyother thing would you like to suggest?
![Screenshot 2024-01-16 022543](https://github.com/ritika728/Wellness_Wave/assets/143774541/3fe0b4fc-93ae-4b38-9b08-9ac87dcb5262)

**Comment by Hemant5104** [comment]
I have manually added the footers to all pages.Is there anything you else you would like to suggest about this??

**Comment by Hemant5104** [comment]
How will I commit changes to main branch.or I show my participance in JWOC'24 as this is my first time in opensource contribution

**Comment by ritika728** [comment]
I have received your pull request. I'll review it & as soon as it gets merge with the relevant labels attached, your participation in JWOC would be considered.
