### ISSUE TITLE
 Calculators Alignment for Consistency 

### ISSUE THREAD

**Issue by ritika728** [ritika728/Wellness_Wave#9]
The current alignment of boxes on the **Tracking page** lacks consistency, leading to a less polished user interface. This issue addresses the need to standardize the alignment of boxes across all calculators on the page.

**Comment by diyabhandari** [comment]
Hi ! Can you please assign me this issue for JWoC '24?

**Comment by Sruti-sahini** [comment]
Hello @ritika728 !
I am from JWoC'24
I have a good hold in web development.
Could you please assign me this issue after the coding period starts?

**Comment by ritika728** [comment]
@Sruti-sahini Only the comments made after the coding period starts would be considered

**Comment by Sruti-sahini** [comment]
Hello @ritika728 
Please assign me this issue under JWoC'24

**Comment by Seema-bedara** [comment]
Hi,                                                                                                                                                                                                                           I am from JWoC'24 .                                                                                                                                                                                                            I am interested in contributing to this as a part of JWOC.`24 Please assign it to me.

**Comment by ritika728** [comment]
@Sruti-sahini assigned

**Comment by Sruti-sahini** [comment]
I have raised the PR. Please accept it.

**Comment by ritika728** [comment]
@Sruti-sahini I haven't received any pull request for this issue yet. Ple

> I have raised the PR. Please accept it.

I haven't received any pull request for this issue yet. Kindly check
