### ISSUE TITLE
addition of pregnancy due date calculator

### ISSUE THREAD

**Issue by GhoshAditi** [ritika728/Wellness_Wave#90]
i would like to add a pregnancy due date calculator . it takes your first day of your last menstrual cycle into account and calculate your due date accordingly based on scientific calculations.
i would like to work on it. plz assign it to me under jwoc'24.

**Comment by GhoshAditi** [comment]
@ritika728 plz assign it to me under jwoc'24.

**Comment by ritika728** [comment]
@GhoshAditi assigned
