### ISSUE TITLE
Lean Body Mass Calculator

### ISSUE THREAD

**Issue by Surajit0573** [ritika728/Wellness_Wave#95]
I want to add a Lean Body Mass Calculator, This Calculator computes a person's estimated lean body mass (LBM) based on body weight, height, gender, and age.

Lean body mass (LBM) is a part of body composition that is defined as the difference between total body weight and body fat weight. This means that it counts the mass of all organs except body fat, including bones, muscles, blood, skin, and everything else. 

Please assign me under JWOC 2024, if approve.

**Comment by ritika728** [comment]
@Surajit0573 go ahead
